services:
  authservice:
    build:
      context: ./AuthService/AuthService
      dockerfile: Dockerfile
    ports:
      - "32770:8080"
    env_file:
      - ./AuthService/AuthService/.env
    restart: always

  tagservice:
    build:
      context: ./TagService/TagService
      dockerfile: Dockerfile
    ports:
      - "32771:8080"
    env_file:
      - ./TagService/TagService/.env
    restart: always

  groupservice:
    build:
      context: ./GroupService_CleanArchitecture
      dockerfile: Dockerfile
    ports:
      - "32772:8080"
    env_file:
      - ./GroupService_CleanArchitecture/Presentation/.env
    restart: always

  todoservice:
    build:
      context: ./ToDoService/ToDoService
      dockerfile: Dockerfile
    ports:
      - "32773:8080"
    env_file:
      - ./ToDoService/ToDoService/.env
    restart: always

  # attachmentservice: